### ISSUE TITLE
Random shutdowns with v. 1.0.13 and kernel 5.10

### ISSUE THREAD

**Issue by lorenzosu** [tuxedocomputers/tuxedo-control-center#117]
Machine: TUXEDO Book BC1507
Tuxedo control center v 1.0.13.
Tuxedo keyboard v 3.0.5
Both installed via pacman in Manjaro.
This happens with kernel 5.10.36-2-MANJARO

Unfortunately the shutdowns are totally random, although maybe they seem to happen more frequently when the power is plugged in (but this is totally non-scientific). Any hint on how to possibly debug or any logs to search would be appreciated.

Similar problem had also been reported around October 2020 via the Tuxedo ticketing ticket # 990648071

Thanks.
Lorenzo.

**Comment by tuxedoxt** [comment]
Hello,

this sounds like a known problem and related to https://github.com/tuxedocomputers/tuxedo-keyboard/issues/78 but with different symptoms.

For most devices this is solved already (by EC update). For yours, this is still in the works.

Basically it's a bug in the EC related to the communication with it and internal keyboard usage. If you lessen the communication (ie not using TCC) **or** do not use the internal keyboard, the occurrences will/should be lessened.

I'll try to reply when we have a fix. Otherwise best (and official) way to get updated would be to get in contact with support if not already, then you should be notified when the fixed EC is available.

**Comment by lorenzosu** [comment]
@tuxedoherbert thanks. However in the tuxedo page for ' Downloads for your TUXEDO' I only see BIOS updates from March 2019?

**Comment by tuxedoxt** [comment]
For reference the EC version should be `EC 1.07.15TR1`.

**Comment by lorenzosu** [comment]
As of today, the suggested EC update by support is still not working nor solved the issue (from the downloads page, see ticket 990840092), so this bug should be re-opened also for the benefit of other users. This is essentially there since October 2020.
