### ISSUE TITLE
2.1.3: no cpu temperature, no cpu fan, no iGPU frequency

### ISSUE THREAD

**Issue by munix9** [tuxedocomputers/tuxedo-control-center#353]
After the update to tuxedo-control-center 2.1.3 and tuxedo-drivers 4.1.0 tuxedo-control-center shows no cpu temperature and no cpu fan - see screenshot.

Infos:
DMI: TUXEDO TUXEDO InfinityBook S 15/17 Gen7/NS5x_7xPU, BIOS 1.07.09RTR2 11/17/2022

openSUSE Tumbleweed 20240116
Linux 6.6.11-1-default

I found the following in the journal:
```
tccd[1236]: Daemon started
tccd[1236]: (node:1236) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'tableCPU' of undefined
tccd[1236]:     at FanControlWorker.setPreviousValues (/snapshot/tuxedo-control-center/dist/tuxedo-control-center/service-app/service-app/classes/FanControlWorker.js)
tccd[1236]:     at FanControlWorker.updateFanLogic (/snapshot/tuxedo-control-center/dist/tuxedo-control-center/service-app/service-app/classes/FanControlWorker.js)
tccd[1236]:     at FanControlWorker.initFanControl (/snapshot/tuxedo-control-center/dist/tuxedo-control-center/service-app/service-app/classes/FanControlWorker.js)
tccd[1236]:     at FanControlWorker.setupTuxedoIO (/snapshot/tuxedo-control-center/dist/tuxedo-control-center/service-app/service-app/classes/FanControlWorker.js)
tccd[1236]:     at FanControlWorker.<anonymous> (/snapshot/tuxedo-control-center/dist/tuxedo-control-center/service-app/service-app/classes/FanControlWorker.js)
tccd[1236]:     at Generator.next (<anonymous>)
tccd[1236]:     at fulfilled (/snapshot/tuxedo-control-center/node_modules/tslib/tslib.js)
tccd[1236]: (Use `tccd --trace-warnings ...` to show where the warning was created)
tccd[1236]: (node:1236) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
tccd[1236]: (node:1236) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
tccd[1236]: Failed executing onWork() => TypeError: Cannot read property 'tableCPU' of undefined
tccd[1236]: Failed executing onWork() => TypeError: Cannot read property 'tableCPU' of undefined
tccd[1236]: Failed executing onWork() => TypeError: Cannot read property 'tableCPU' of undefined
tccd[1236]: Failed executing onWork() => TypeError: Cannot read property 'tableCPU' of undefined
...
```

![scr](https://github.com/tuxedocomputers/tuxedo-control-center/assets/44939650/50567431-f826-4e3c-ab10-444a75c498f6)

In addition, the tccd constantly floods the log with the message:
```
tccd[1236]: Failed executing onWork() => TypeError: Cannot read property 'tableCPU' of undefined
```
A new line every second.

**Comment by salihmarangoz** [comment]
Same here. 

Also, it would be nice to be able to roll back to the previous version, but unfortunately, it is not on the APT server anymore.

**Comment by munix9** [comment]
I also noticed that the iGPU frequency is not available or grayed out - see also the screenshot.

I also looked at https://github.com/tuxedocomputers/tuxedo-control-center/issues/346 and noticed that the code assumes `/sys/class/drm/card0/`, but only `/sys/class/drm/card1/` exists on my notebook.

So something doesn't seem to be working correctly there either.

```
$ ls -l /sys/class/drm/
lrwxrwxrwx 1 root root    0 Jan 18 07:00 card1 -> ../../devices/pci0000:00/0000:00:02.0/drm/card1
lrwxrwxrwx 1 root root    0 Jan 18 07:00 card1-DP-1 -> ../../devices/pci0000:00/0000:00:02.0/drm/card1/card1-DP-1
lrwxrwxrwx 1 root root    0 Jan 18 07:00 card1-DP-2 -> ../../devices/pci0000:00/0000:00:02.0/drm/card1/card1-DP-2
lrwxrwxrwx 1 root root    0 Jan 18 07:00 card1-DP-3 -> ../../devices/pci0000:00/0000:00:02.0/drm/card1/card1-DP-3
lrwxrwxrwx 1 root root    0 Jan 18 07:00 card1-DP-4 -> ../../devices/pci0000:00/0000:00:02.0/drm/card1/card1-DP-4
lrwxrwxrwx 1 root root    0 Jan 18 07:00 card1-HDMI-A-1 -> ../../devices/pci0000:00/0000:00:02.0/drm/card1/card1-HDMI-A-1
lrwxrwxrwx 1 root root    0 Jan 18 07:00 card1-eDP-1 -> ../../devices/pci0000:00/0000:00:02.0/drm/card1/card1-eDP-1
lrwxrwxrwx 1 root root    0 Jan 18 07:00 renderD128 -> ../../devices/pci0000:00/0000:00:02.0/drm/renderD128
-r--r--r-- 1 root root 4096 Jan 18 09:34 version
```

**Comment by sketchbuch** [comment]
https://www.reddit.com/r/tuxedocomputers/comments/199jmyi/tcc_v213_constant_fan_and_broken_guages_pulse_15/

**Comment by Bundy01** [comment]
I've also noticed that the temperature management doesn't work with the latest version, the fan doesn't start and the CPU temperature can exceed 90°C :/.

**Comment by salihmarangoz** [comment]
Downgraded back to 2.1.2 and it works again. Build it yourself:

Steps to build (for deb package):
```bash
git clone https://github.com/tuxedocomputers/tuxedo-control-center.git -b v2.1.2
cd tuxedo-control-center
npm install
npm run pack-prod deb
```

If you are too lazy to build it, I don't recommend installing a package that a stranger provides, but here is the deb file that I built: [gdrive link](https://drive.google.com/file/d/17gWe8X-wUvhy0RCWeIeIjYkXuSq_MNlE/view?usp=sharing).

After the installation, exit tuxedo control center and restart tccd:
```bash
sudo service tccd restart
```

@tuxedoxt is it possible to provide binaries in the "Release" section?

**Comment by sketchbuch** [comment]
I'll stick to 2.0.8 for now as it also fixes this issue: https://www.reddit.com/r/tuxedocomputers/comments/18rybx9/any_fix_soon_for_fans_being_on_max_when_waking/

**Comment by munix9** [comment]
This doesn't necessarily belong here and maybe I'll open a separate issue for it, but ...

Why is [logLine code](https://github.com/tuxedocomputers/tuxedo-control-center/blob/master/src/service-app/classes/TuxedoControlCenterDaemon.ts#L838) disabled and instead stdout (and thus the journal) is cluttered with messages ([see](https://github.com/tuxedocomputers/tuxedo-control-center/blob/master/src/service-app/classes/TuxedoControlCenterDaemon.ts#L147))?!

For the time being the `tccd.service` could be extended, e.g. with
```
StandardOutput=truncate:/var/log/tccd/log
StandardError=truncate:/var/log/tccd/log
```

**Comment by tuxedoxt** [comment]
Hello,

I pushed a quick fix regarding fan control. Please try v2.1.4.

**Comment by salihmarangoz** [comment]
> Hello,
> 
> I pushed a quick fix regarding fan control. Please try v2.1.4.

Thanks v2.1.4 solves the device control problem. But still, I see logs printed every second in the journal like this:

```
Jan 18 16:09:23 stellaris tccd[312049]: Failed executing onWork() => Error: Command failed: export XAUTHORITY=/home/salih/.Xauthority && xrandr -q -display :1 --current
Jan 18 16:09:23 stellaris tccd[312049]: No protocol specified
Jan 18 16:09:23 stellaris tccd[312049]: Can't open display :1
```

**Comment by munix9** [comment]
> Hello,
> 
> I pushed a quick fix regarding fan control. Please try v2.1.4.

It looks better now. cpu temperature and cpu fan seem to work again, iGPU frequency is still without function.

![scr](https://github.com/tuxedocomputers/tuxedo-control-center/assets/44939650/e9b616a6-4f50-4a0e-bb39-505d1fcf3d46)

**Comment by sketchbuch** [comment]
Still have issues with empty guages in 2.1.4 and constant fan with temp showing nearly 90 dgrees on idle.

Pulse 15 Gen 1 - Ubuntu 22.04 (from WebFAI)

![Screenshot from 2024-01-19 04-56-13](https://github.com/tuxedocomputers/tuxedo-control-center/assets/16445037/94efaa5d-290c-453d-b00f-321246ed1ab0)

**Comment by munix9** [comment]
> Hello,
> 
> > It looks better now. cpu temperature and cpu fan seem to work again, iGPU frequency is still without function (I doubt that the display of iGPU - Power is correct and works, because it always says 0 W).
> 
> Regarding other dashboard issues, flexible paths etc there will be another fix.
> 

Ok, thanks.
One more comment on this:
I'm not sure which values are read from which source, from `src/service-app/classes/GpuInfoWorker.ts` I get
```
cur_freq: /sys/class/drm/card0/gt_act_freq_mhz
max_freq: /sys/class/drm/card0/gt_RP0_freq_mhz
```
On my notebook (InfinityBook S 15/17 Gen7/NS5x_7xPU) the following values result for `card1`:
```
$ cat /sys/class/drm/card1/gt_act_freq_mhz
0
$ cat /sys/class/drm/card1/gt_RP0_freq_mhz
1400
```
`gt_act_freq_mhz` is probably not useful here, `gt_cur_freq_mhz` looks more correct:
```
$ cat /sys/class/drm/card1/gt_cur_freq_mhz
300
```
But I'm still researching which values are sensible and correct, and I'm sure you have much more knowledge about this.

**Comment by sketchbuch** [comment]
> High fan speed and high temp sounds like high load in general. Check for example `top` to see which processes are using a lot of CPU time. If the load is fine but you want a max noise level at the expense of throttling you can play around with the max fan speed parameter or the custom fan curve.

This is no load, it is constnatly on at max with nearly 90 degree cpu temp.

Why should I play around with profiles or look for load when there is none? Just reverting to an older version of the TCC fixes the issue.

**Comment by tuxedoxt** [comment]
> > High fan speed and high temp sounds like high load in general. Check for example `top` to see which processes are using a lot of CPU time. If the load is fine but you want a max noise level at the expense of throttling you can play around with the max fan speed parameter or the custom fan curve.
> 
> This is no load, it is constantly on at max with nearly 90 degree cpu temp.
> 
> Why should I play around with profiles or look for load when there is none? Just reverting to an older version of the TCC fixes the issue.

Alright, that's new. Could you include some info like
- `journalctl -u tccd`
- the profile config `/etc/tcc/profiles`
- output of `dkms status` and `uname -r`

**Comment by err0r2k** [comment]
After upgrading from 2.1.1 to 2.1.4 my GPU disappeared from TCC Dashboard. I use Tuxedo OS 2.
![Screenshot_20240122_221046](https://github.com/tuxedocomputers/tuxedo-control-center/assets/102223210/08a99a2f-bff0-443b-a4fc-47ab78219639)

**Comment by sketchbuch** [comment]
@tuxedoxt 

uname -r
---
6.5.0-10013-tuxedo

dkms status
---
tuxedo-drivers/4.0.3, 6.5.0-10013-tuxedo, x86_64: installed
tuxedo-drivers/4.0.3, 6.5.0-10022-tuxedo, x86_64: installed
virtualbox/7.0.14, 6.5.0-10013-tuxedo, x86_64: installed
virtualbox/7.0.14, 6.5.0-10022-tuxedo, x86_64: installed

/etc/tcc/profiles
---
[{"id":"__default_custom_profile__","name":"TUXEDO Defaults","description":"Edit profile to change behaviour","display":{"brightness":100,"useBrightness":false},"cpu":{"useMaxPerfGov":false,"governor":"powersave","energyPerformancePreference":"balance_performance","noTurbo":false},"webcam":{"status":true,"useStatus":true},"fan":{"useControl":true,"fanProfile":"Balanced","minimumFanspeed":0,"offsetFanspeed":0},"odmProfile":{},"odmPowerLimits":{"tdpValues":[]}}]

journalctl -u tccd
---
![Screenshot from 2024-01-23 09-06-44](https://github.com/tuxedocomputers/tuxedo-control-center/assets/16445037/b0d630af-1cb0-47e2-868b-25fcd1b051bb)

**Comment by tuxedoherbert** [comment]
Hi, would you please update your system (at least kernel, tuxedo-control-center and tuxedo-drivers) to the latest versions please?

**Comment by munix9** [comment]
> Hi, would you please update your system (at least kernel, tuxedo-control-center and tuxedo-drivers) to the latest versions please?

I don't know who you were talking to - I always keep my system up to date:

DMI: TUXEDO TUXEDO InfinityBook S 15/17 Gen7/NS5x_7xPU, BIOS 1.07.09RTR2 11/17/2022
openSUSE Tumbleweed 20240131
Linux kernel 6.7.2-1-default x86_64
tuxedo-drivers 4.1.2
tuxedo-control-center 2.1.5

The display is still like in https://github.com/tuxedocomputers/tuxedo-control-center/issues/353#issuecomment-1898693866 - no change/improvement.

**Comment by sketchbuch** [comment]
@tuxedoherbert 

tcc
---
2.1.6

uname -r
---
6.5.0-10022-tuxedo

dkms status
---
tuxedo-drivers/4.2.1, 6.5.0-10022-tuxedo, x86_64: installed
virtualbox/7.0.14, 6.5.0-10013-tuxedo, x86_64: installed
virtualbox/7.0.14, 6.5.0-10022-tuxedo, x86_64: installed

---

It is a lot better! Good work. The fans still start slightly during boot, and once the greater appears the fans ramp up even the the laptop isn't doing aynthing, about just over a minute aftr logging in the fans have slowly reduced from max to zero. 

It would be good if these issues could be fixed too... but better than always on.

I haven't had time yet to really do anything so i don't know how playing games using kdenlive, or programming affect it but it is certainly better than 2.1.5

**Comment by err0r2k** [comment]
> After upgrading from 2.1.1 to 2.1.4 my GPU disappeared from TCC Dashboard. I use Tuxedo OS 2. ![Screenshot_20240122_221046](https://private-user-images.githubusercontent.com/102223210/298728989-08a99a2f-bff0-443b-a4fc-47ab78219639.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwMTc5MTIsIm5iZiI6MTcwODAxNzYxMiwicGF0aCI6Ii8xMDIyMjMyMTAvMjk4NzI4OTg5LTA4YTk5YTJmLWJmZjAtNDQzYi1hNGZjLTQ3YWI3ODIxOTYzOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNVQxNzIwMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYmNjMjExYTkzOGJjOWJmYmFiMDk3MmJiY2IxZGViM2I5MjViZTMzY2MxMWVjNjAyZjFkODczYzc5MTMyNzc3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.EJXjH47K8vyIDpK2olYd0QUF3X0lKeH5Bd7Zq0XJ_xY)

After Upgrading to 2.1.6, the GPU appear again in TCC Dashboard. Thanks!

**Comment by tuxedoherbert** [comment]
> Fans also still keep switching on to max for about 5 seconds when waking from sleep.

That's a correct behavoir to also wake up the fans and make sure that they are turning.


> Some gauges still have issues: CPU Power, iGPU Temp, and iGPU speed all show n/a when I first open the tcc, and it takes a few seconds for these values to change (Pulse 15 Gen 1).

That's also fine :) It needs a couple of seconds to initialize this, because it needs to collect data over a short period of time to get valid information. If it would collect this all the time, the system wouild have load all the time.

> the fans ramp up to pretty much max, even though the laptop isn't doing aynthing

Please check `top` for system load or the tcc for the temp. The fans should only ramping up if the temp is high. maybe there is some background process (apt/discover/etc.) that is causing some load which leads into higher temp. Do you have your own fan profile configured with very low speed or high temps?

**Comment by tuxedoherbert** [comment]
> > Hi, would you please update your system (at least kernel, tuxedo-control-center and tuxedo-drivers) to the latest versions please?
> 
> I don't know who you were talking to - I always keep my system up to date:
> 
> DMI: TUXEDO TUXEDO InfinityBook S 15/17 Gen7/NS5x_7xPU, BIOS 1.07.09RTR2 11/17/2022 openSUSE Tumbleweed 20240131 Linux kernel 6.7.2-1-default x86_64 tuxedo-drivers 4.1.2 tuxedo-control-center 2.1.5
> 
> The display is still like in [#353 (comment)](https://github.com/tuxedocomputers/tuxedo-control-center/issues/353#issuecomment-1898693866) - no change/improvement.

hi @munix9 , would you please be so kind and recheck with the latest updates?

**Comment by munix9** [comment]
> 
> hi @munix9 , would you please be so kind and recheck with the latest updates?

looks good, thanks!
